### PR TITLE
Add Chinese support

### PR DESCRIPTION
**Pull request by cpuwolf**
#51 Add Chinese string

### CODE REVIEW

**Comment by skiselkov** [comment]
Thank you, this is looking very good! I will commit this in a short moment.

**Comment by skiselkov** [comment]
Squashed and committed with minor icon layout corrections in 42f8c3e. I will need to build a GUI to let you select Chinese as the language, since X-Plane for some reason doesn't have it in its preferences menu.

**Comment by cpuwolf** [comment]
exactly, there is no chinese in XP. usually we choose Japenese and do some crack on it.

**Comment by skiselkov** [comment]
I'll put in a separate preferences window for BetterPushback, so you can change the language without having to rely on X-Plane's UI.

**Comment by cpuwolf** [comment]
Oh, that is great. I am preparing Chinese voice now

**Pull request closed without merging**
