### PR TITLE
add Chinese sound files

### PR DESCRIPTION
**Pull request by cpuwolf**
#51 special thanks to @ces机师 @民航机务论坛 @逆流而上的溪水 @chaizhansen @古都无船 @Wing--Whisper @Last_Wwhisper @莪是黑曼巴 @Rifleman- they all from weibo.com

### CODE REVIEW

**Comment by skiselkov** [comment]
I'm looking at done_left.mp3 and done_right.mp3 and they're the same file. Can you please check.

**Comment by cpuwolf** [comment]
exactly, I check with real ground staff, they dont say left and right in China, that is why they are same

**Comment by skiselkov** [comment]
Interesting. Then how do they tell you where to look for them to give the captain the "all-clear signal" after they have disconnected the towing vehicle?

**Comment by cpuwolf** [comment]
yes, they only say "please watch my hand signal " in real cases in China. Left or Right, only two possible cases, and pilot always know where they go after disconnecting tow.

**Comment by skiselkov** [comment]
I have cherry-picked this and cleaned it up a bit to give the audio the same kinds of volume compression and distortion as the rest of the audio packs. Thanks for your contribution!

**Pull request closed without merging**
