### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by Semirben**
Fixed typos and corrected translations to a better wording

### CODE REVIEW

**Comment by skiselkov** [comment]
If I may place another request, I'd appreciate if you could translate & record the audio messages. Just plain audio, I'll add the radio distortion & noise later. You'll find the English audio files in `data/msgs/en`. Let me know if you need the English text and/or a (bad) German translation of it :)

**Comment by Semirben** [comment]
I have to see if I find the time to record them but I can't promise a definite time frame :)

**Comment by skiselkov** [comment]
Well until then people might just have to put up with my stupid accent :)
Anyway thanks for your great help with this.

**Comment by liebbe10** [comment]
Hey,
Working on a translation of the spoken text into german. Don't know what the winch.wav file is saying...

**Comment by Semirben** [comment]
Seems to be "Winching strap and adapter in position. Release parking brake when ready to start pushback"

**Comment by skiselkov** [comment]
@liebbe10 Thanks for the help. I've created a new feature issue to track this with all the messages texts: https://github.com/skiselkov/BetterPushbackC/issues/41

**Pull request merged**
